# This file is generated by Dist::Zilla
# Prereqs are detected automatically. You do not need to edit this file

requires "Test::Harness" => "3.44";

on 'test' => sub {
  requires "Test::Harness" => "3.44";
  requires "Test::Simple" => "1.302192";
};

on 'configure' => sub {
  requires "ExtUtils::MakeMaker" => "0";
};
